# -*- coding: utf-8 -*-
"""[AS] Yuji's Automated Typesetting and Compiling Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3ErJLGHqFpvRYyyHbiE-VhFQI3AwNe-

**INSTRUCTIONS!!!**

1.   Click Play on Step 1 and click "Allow" when Google asks to connect to Drive.

2. Click the Folder icon 📁 on the left, expand the drive folder, then MyDrive, and navigate to where the Excel file is saved.

3. Click the three dots ⋮ next to the Excel file and select "Copy path". The path must be leading to the **ONLY** .xlsx file where your input data is contained.

4. Paste that path into the INPUT_FILE_PATH box in Step 2.

5. Click Play on Step 2. The finished Word document will automatically download to your computer.
"""

# @title Step 1: Click the Play Button.
# @markdown Click Play to connect your Google Drive. A popup will ask for permission.
from google.colab import drive
drive.mount('/content/drive')

!pip install python-docx pandas openpyxl -q
print("✅ CLEARED! You can now go to Step 2.")

# @title Step 2: Click the Play Button again.
# @markdown Run this cell after setting your file path below.

# @markdown ---
# @markdown ### **Path Settings**
INPUT_FILE_PATH = "" # @param {type:"string"}
OUTPUT_FILE_NAME = "Philippine_Hokkien_Dictionary.docx" # @param {type:"string"}
# @markdown ---

import pandas as pd
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
import unicodedata
import re

# --- CONFIGURATION (Handled by Form above) ---
ORANGE = RGBColor(237, 125, 49)

def get_sort_keys(hokkien_word):
    """
    Implements flowchart sorting:
    1. Base syllables (ignoring tones)
    2. Tones (syllable by syllable)
    3. Original string fallback
    Skips leading '--' and '...-' prefixes.
    """
    if pd.isna(hokkien_word):
        return ([], [], "")

    word_str = str(hokkien_word).lower()

    clean_word = re.sub(r'\s*\(\d+\)$', '', word_str)
    clean_word = re.sub(r'^(--|\.\.\.-)', '', clean_word)
    syllables = re.split(r'-+', clean_word)

    bases = []
    tones = []

    diacritic_map = {
        '\u0301': 2, # Acute
        '\u0300': 3, # Grave
        '\u0302': 4, # Circumflex
        '\u030C': 5, # Caron
        '\u0304': 6, # Horizontal bar
        '\u030D': 7  # Vertical line above
    }

    for syl in syllables:
        if not syl:
            continue

        nfd_form = unicodedata.normalize('NFD', syl)
        base_str = ""
        diacritic_rank = 1

        for char in nfd_form:
            if unicodedata.category(char) == 'Mn':
                if char in diacritic_map and diacritic_map[char] > diacritic_rank:
                    diacritic_rank = diacritic_map[char]
            else:
                base_str += char

        bases.append(base_str)
        tones.append(diacritic_rank)

    return (bases, tones, word_str)

def apply_font_settings(run, bold=False, color=None):
    """Utility to enforce Cambria 11pt and specific colors/weights."""
    run.font.name = 'Cambria'
    run.font.size = Pt(11)
    run.bold = bold
    if color:
        run.font.color.rgb = color

def generate_dictionary():
    print(f"Reading Excel data from path: {INPUT_FILE_PATH} ...")
    try:
        df = pd.read_excel(INPUT_FILE_PATH)
    except FileNotFoundError:
        print(f"❌ ERROR: Could not find a file at '{INPUT_FILE_PATH}'. Please check the path and try again.")
        return False

    print("Sorting data by syllable and diacritics...")
    df['sort_keys'] = df['hokkien'].apply(get_sort_keys)
    df = df.sort_values(by=['sort_keys']).reset_index(drop=True)

    duplicate_counts = df.groupby('hokkien').cumcount() + 1
    total_counts = df.groupby('hokkien')['hokkien'].transform('count')

    print("Initializing Word Document...")
    doc = Document()

    section = doc.sections[0]
    sectPr = section._sectPr
    cols = OxmlElement('w:cols')
    cols.set(qn('w:num'), '2')
    cols.set(qn('w:space'), '720')
    sectPr.append(cols)

    print("Generating entries...")
    for idx, row in df.iterrows():
        if pd.isna(row['hokkien']):
            continue

        p = doc.add_paragraph()
        p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.LEFT
        p.paragraph_format.line_spacing = 1.15
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after = Pt(6)

        # 1. Hokkien
        hokkien_word = str(row['hokkien'])
        r_hokkien = p.add_run(hokkien_word)
        apply_font_settings(r_hokkien, bold=True, color=ORANGE)

        if total_counts[idx] > 1:
            r_dup = p.add_run(f" ({duplicate_counts[idx]})")
            apply_font_settings(r_dup, bold=True, color=ORANGE)

        p.add_run(" ")

        # 2. Lannang
        if not pd.isna(row['lannang']):
            r_lan = p.add_run(f"[{str(row['lannang'])}] ")
            apply_font_settings(r_lan)

        # 3. Hanzi
        if not pd.isna(row['hanzi']):
            r_han = p.add_run(f"{str(row['hanzi'])} ")
            apply_font_settings(r_han)

        # 4. Variants
        if not pd.isna(row['variants']):
            r_var_start = p.add_run("[var. ")
            apply_font_settings(r_var_start)
            r_var_val = p.add_run(str(row['variants']))
            apply_font_settings(r_var_val, color=ORANGE)
            r_var_end = p.add_run("] ")
            apply_font_settings(r_var_end)

        # --- MULTI-DEFINITION LOGIC ---
        defs = []
        col_idx = 4
        while col_idx + 3 < len(df.columns) - 1:
            v_type = row.iloc[col_idx] if not pd.isna(row.iloc[col_idx]) else None
            v_label = row.iloc[col_idx+1] if not pd.isna(row.iloc[col_idx+1]) else None
            v_meaning = row.iloc[col_idx+2] if not pd.isna(row.iloc[col_idx+2]) else None
            v_syn = row.iloc[col_idx+3] if not pd.isna(row.iloc[col_idx+3]) else None

            if v_type or v_label or v_meaning or v_syn:
                defs.append({'type': v_type, 'label': v_label, 'meaning': v_meaning, 'syn': v_syn})
            col_idx += 4

        if not defs:
            continue

        has_empty_labels = any(not d['label'] for d in defs)
        active_labels = [d['label'] for d in defs if d['label']]

        shared_label = None
        if not has_empty_labels and active_labels and all(l == active_labels[0] for l in active_labels):
            shared_label = active_labels[0]

        if shared_label:
            r_shared_lbl = p.add_run(f"⟨{shared_label}⟩ ")
            apply_font_settings(r_shared_lbl)

        groups = []
        current_type = -1
        for d in defs:
            t_val = d['type'] if d['type'] else ""
            if t_val != current_type:
                groups.append({'type': t_val, 'entries': []})
                current_type = t_val
            groups[-1]['entries'].append(d)

        for g_idx, group in enumerate(groups):
            if g_idx > 0:
                p.add_run(" • ")

            if group['type']:
                r_type = p.add_run(f"{group['type']} ")
                apply_font_settings(r_type)

            entries = group['entries']
            is_multi_meaning = len(entries) > 1

            for i, entry in enumerate(entries):
                if entry['label'] and not shared_label:
                    r_lbl = p.add_run(f"⟨{entry['label']}⟩ ")
                    apply_font_settings(r_lbl)

                if is_multi_meaning:
                    r_num = p.add_run(f"{i+1}. ")
                    apply_font_settings(r_num)

                if entry['meaning']:
                    mean_str = str(entry['meaning']).strip() + " "
                    r_mean = p.add_run(mean_str)
                    apply_font_settings(r_mean)

                if entry['syn']:
                    r_syn_start = p.add_run("(Syn.: ")
                    apply_font_settings(r_syn_start)
                    r_syn_val = p.add_run(str(entry['syn']))
                    apply_font_settings(r_syn_val, color=ORANGE)
                    r_syn_end = p.add_run(") ")
                    apply_font_settings(r_syn_end)

    print(f"Saving to {OUTPUT_FILE_NAME}...")
    doc.save(OUTPUT_FILE_NAME)
    print("✅ Congratulations! Your dictionary has been generated successfully.")
    return True

if __name__ == "__main__":
    success = generate_dictionary()

    if success:
        try:
            from google.colab import files
            print(f"📥 Downloading {OUTPUT_FILE_NAME} to your computer...")
            files.download(OUTPUT_FILE_NAME)
        except ImportError:
            pass